package test

const BookResponse = `[
    {
        "onix":{
            "CollateralDetail":{
                "SupportingResource":[
                    {
                        "ResourceContentType":"01",
                        "ResourceMode":"03",
                        "ContentAudience":"01",
                        "ResourceVersion":[
                            {
                                "ResourceLink":"https://example.com/yyy.jpg",
                                "ResourceForm":"02",
                                "ResourceVersionFeature":[
                                    {
                                        "ResourceVersionFeatureType":"01",
                                        "FeatureValue":"D502"
                                    },
                                    {
                                        "ResourceVersionFeatureType":"04",
                                        "FeatureValue":"9784780802047.jpg"
                                    }
                                ]
                            }
                        ]
                    }
                ],
                "TextContent":[
                    {
                        "Text":"dummy_brief_description",
                        "TextType":"02",
                        "ContentAudience":"00"
                    },
                    {
                        "Text":"dummy_description",
                        "TextType":"03",
                        "ContentAudience":"00"
                    },
                    {
                        "Text":"dummy_toc",
                        "TextType":"04",
                        "ContentAudience":"00"
                    }
                ]
            },
            "PublishingDetail":{
                "Imprint":{
                    "ImprintName":"技術評論社",
                    "ImprintIdentifier":[
                        {
                            "IDValue":"7741",
                            "ImprintIDType":"19"
                        }
                    ]
                },
                "PublishingDate":[
                    {
                        "Date":"",
                        "PublishingDateRole":"01"
                    }
                ]
            },
            "ProductSupply":{
                "SupplyDetail":{
                    "ReturnsConditions":{
                        "ReturnsCode":"02",
                        "ReturnsCodeType":"04"
                    },
                    "ProductAvailability":"99"
                }
            },
            "NotificationType":"03",
            "ProductIdentifier":{
                "IDValue":"9784774183923",
                "ProductIDType":"15"
            },
            "RecordReference":"9784774183923",
            "DescriptiveDetail":{
                "TitleDetail":{
                    "TitleType":"01",
                    "TitleElement":{
                        "TitleElementLevel":"01",
                        "TitleText":{
                            "content":"みんなのGo言語 : 現場で使える実践テクニック",
                            "collationkey":"ミンナ ノ Goゲンゴ : ゲンバ デ ツカエル ジッセン テクニック"
                        }
                    }
                },
                "Language":[
                    {
                        "LanguageCode":"jpn",
                        "LanguageRole":"01",
                        "CountryCode":"JP"
                    }
                ],
                "ProductForm":"BZ",
                "Extent":[
                    {
                        "ExtentValue":"143",
                        "ExtentUnit":"03",
                        "ExtentType":"11"
                    }
                ],
                "Measure":[
                    {
                        "MeasureType":"01",
                        "MeasureUnitCode":"mm",
                        "Measurement":"260"
                    },
                    {
                        "MeasureType":"02",
                        "MeasureUnitCode":"mm",
                        "Measurement":"0"
                    }
                ],
                "Contributor":[
                    {
                        "ContributorRole":[
                            "A01"
                        ],
                        "PersonName":{
                            "content":"mattn"
                        },
                        "SequenceNumber":"1"
                    },
                    {
                        "ContributorRole":[
                            "A01"
                        ],
                        "PersonName":{
                            "content":"中島 大一"
                        },
                        "SequenceNumber":"2"
                    },
                    {
                        "ContributorRole":[
                            "A01"
                        ],
                        "PersonName":{
                            "content":"牧 大輔"
                        },
                        "SequenceNumber":"3"
                    },
                    {
                        "ContributorRole":[
                            "A01"
                        ],
                        "PersonName":{
                            "content":"藤原 俊一郎"
                        },
                        "SequenceNumber":"4"
                    },
                    {
                        "ContributorRole":[
                            "A01"
                        ],
                        "PersonName":{
                            "content":"鈴木 健太"
                        },
                        "SequenceNumber":"5"
                    },
                    {
                        "ContributorRole":[
                            "A01"
                        ],
                        "PersonName":{
                            "content":"松木 雅幸"
                        },
                        "SequenceNumber":"6"
                    }
                ],
                "ProductComposition":"00"
            }
        },
        "hanmoto":{
            "dateshuppan":"2016-10",
            "datemodified":"2016-09-27 21:06:21",
            "datecreated":"2016-09-27 21:06:21"
        },
        "summary":{
            "publisher":"技術評論社",
            "isbn":"9784774183923",
            "pubdate":"2016-10",
            "title":"みんなのGo言語 : 現場で使える実践テクニック",
            "series":"dummy_series",
            "author":"mattn／著 中島大一／著 牧大輔／著 藤原俊一郎／著 鈴木健太／著 松木雅幸／著",
            "cover":"http://example.com/xxx.jpg",
            "volume":"dummy_volume"
        }
    }
]
`
